insert into cart (user_id, status) values (1,'A');
insert into cart (user_id, status) values (2,'A');
insert into cart (user_id, status) values (5,'A');
insert into cart (user_id, status) values (3,'A');
insert into cart (user_id, status) values (2,'C');
insert into cart (user_id, status) values (4,'C');
insert into cart (user_id, status) values (5,'A');
insert into cart (user_id, status) values (2,'C');
insert into cart (user_id, status) values (1,'C');
insert into cart (user_id, status) values (1,'A');
insert into cart (user_id, status) values (2,'C');
insert into cart (user_id, status) values (4,'A');
insert into cart (user_id, status) values (3,'C');
insert into cart (user_id, status) values (4,'A');
insert into cart (user_id, status) values (5,'C');
insert into cart (user_id, status) values (3,'A');
insert into cart (user_id, status) values (2,'C');
insert into cart (user_id, status) values (1,'C');
insert into cart (user_id, status) values (5,'A');
insert into cart (user_id, status) values (2,'A');
insert into category(name) values ('Administrador');
insert into category(name) values ('Cliente');
insert into detailcart (cart_id, product_id, cantidad) values (1, 16, 2);
insert into detailcart (cart_id, product_id, cantidad) values (2, 18, 2);
insert into detailcart (cart_id, product_id, cantidad) values (3, 7, 3);
insert into detailcart (cart_id, product_id, cantidad) values (4, 13, 3);
insert into detailcart (cart_id, product_id, cantidad) values (5, 12, 2);
insert into detailcart (cart_id, product_id, cantidad) values (1, 1, 2);
insert into detailcart (cart_id, product_id, cantidad) values (2, 14, 3);
insert into detailcart (cart_id, product_id, cantidad) values (3, 15, 4);
insert into detailcart (cart_id, product_id, cantidad) values (4, 18, 4);
insert into detailcart (cart_id, product_id, cantidad) values (5, 8, 2);
insert into detailcart (cart_id, product_id, cantidad) values (6, 3, 2);
insert into detailcart (cart_id, product_id, cantidad) values (7, 18, 2);
insert into detailcart (cart_id, product_id, cantidad) values (8, 12, 3);
insert into detailcart (cart_id, product_id, cantidad) values (9, 13, 3);
insert into detailcart (cart_id, product_id, cantidad) values (10, 15, 4);
insert into detailcart (cart_id, product_id, cantidad) values (6, 14, 4);
insert into detailcart (cart_id, product_id, cantidad) values (7, 3, 2);
insert into detailcart (cart_id, product_id, cantidad) values (8, 18, 2);
insert into detailcart (cart_id, product_id, cantidad) values (9, 13, 3);
insert into detailcart (cart_id, product_id, cantidad) values (10, 7, 3);
insert into detailcart (cart_id, product_id, cantidad) values (11, 6, 3);
insert into detailcart (cart_id, product_id, cantidad) values (12, 2, 3);
insert into detailcart (cart_id, product_id, cantidad) values (13, 18, 3);
insert into detailcart (cart_id, product_id, cantidad) values (14, 14, 2);
insert into detailcart (cart_id, product_id, cantidad) values (15, 4, 4);
insert into detailcart (cart_id, product_id, cantidad) values (16, 2, 2);
insert into detailcart (cart_id, product_id, cantidad) values (17, 8, 4);
insert into detailcart (cart_id, product_id, cantidad) values (18, 17, 2);
insert into detailcart (cart_id, product_id, cantidad) values (19, 18, 4);
insert into detailcart (cart_id, product_id, cantidad) values (20, 10, 3);
insert into detailcart (cart_id, product_id, cantidad) values (11, 4, 3);
insert into detailcart (cart_id, product_id, cantidad) values (12, 17, 2);
insert into detailcart (cart_id, product_id, cantidad) values (13, 10, 2);
insert into detailcart (cart_id, product_id, cantidad) values (14, 18, 4);
insert into detailcart (cart_id, product_id, cantidad) values (15, 2, 2);
insert into detailcart (cart_id, product_id, cantidad) values (16, 18, 3);
insert into detailcart (cart_id, product_id, cantidad) values (17, 12, 2);
insert into detailcart (cart_id, product_id, cantidad) values (18, 17, 3);
insert into detailcart (cart_id, product_id, cantidad) values (19, 12, 2);
insert into detailcart (cart_id, product_id, cantidad) values (20, 15, 3);
insert into genres (id, name) values (1, 'Literatura');
insert into genres (id, name) values (2, 'Consulta y referencia');
insert into genres (id, name) values (3, 'Artistico e ilustrado');
insert into genres (id, name) values (4, 'Divulgativo');
insert into genres (id, name) values (5, 'Texto');
insert into genres (id, name) values (6, 'Tecnico');
insert into genres (id, name) values (7, 'Practico');
insert into genres (id, name) values (8, 'Religion');
insert into genres (id, name) values (9, 'Autoayuda');
insert into genres (id, name) values (10, 'Infantil');
INSERT INTO products(title,author,genre_id,description,descriptionD,publisher,imgTop,imgBack,alt,price,discount,category,stock) VALUES 
('Inteligencia emocional',' Fabian Goleman','4','El éxito y la superación personal pueden parecer un regalo destinado solo a algunos pocos privilegiados. En realidad, pueden ser alcanzados por cualquier persona gracias a todo aquello que vas a descubrir y aprender entre las páginas de este magnífico libro','En poco tiempo podrás percibir y apreciar enormes beneficios en tu vida, como; • A dirigirte a cualquier persona con confianza y firmeza. • Aprenderás hábitos saludables que van a mejorar y organizar tu vida. • Percibirás un aumento de calidad en las relaciones personales e interpersonales. • Vas a adquirir un estado de ánimo capaz de afrontar los problemas de manera audaz y concisa. ¡Y AÚN, MUCHO MÁS!','','libro10a.png','libro10b.png','producto-1',15000,'12','visited',2),
('Sabiduría Financiera','Raimon Samso','1','Hay muchos libros sobre “inteligencia financiera” pero pocos de “sabiduría financiera”. El autor es conocido por combinar la economía con la consciencia y ofrecer una visión que va más allá de lo mundano para adentrarse en la espiritualidad. Como experto en educación financiera, defiende la necesidad de iluminar todos los asuntos de la vida, incluido los del dinero. Este libro de sabiduría financiera comparable al Piense y hágase rico es educación financiera para no financieros, un libro de educación financiera y como manejar finanzas.',' Con este inusual libro, podrás cambiar tu forma de pensar para mejorar tu situación económica. • Aprenderás a ver oportunidades donde antes solo veías problemas económicos. • Pensarás como las personas más prósperas, y podrás alcanzar los resultados financieros que tanto deseas. • Este libro revelador te ayudará a cambiar tu vida para mejor, y podrás lograr la libertad financiera. La “sabiduría financiera” es el nuevo paradigma en el “economía consciente”, un libro de emprendedores, y engloba: valores, principios, integridad, ética, emociones, espiritualidad; y por supuesto, compasión y bondad. Te conduce, más allá de la “libertad financiera” con ingresos pasivos, a un estado de certeza económica con un negocio sabio que se nutre de la inteligencia del Cosmos. Una persona “sabia financieramente” utiliza su conocimiento y experiencia con bondad, lo que le permite tomar mejores decisiones y ser siempre optimista al margen de los resultados que obtenga.','','libro20a.png','libro20b.png','producto-2',25000,'10','in-sale',2),
('El secreto de la paz personal','Billy Graham','5','El secreto de la paz personal incluye verdades bíblicas confiables por el renombrado evangelista, doctor Billy Graham, haciendo de este libro un regalo perfecto para evangelismo o alcance.','La gente está buscando respuestas a la confusión, la enfermedad moral y el vacío espiritual que oprime al mundo. Todos estamos clamando por dirección, por consuelo, por paz. ¿Hay alguna salida para nuestro dilema? ¿Podemos verdaderamente encontrar paz con Dios? ¡Sí! Pero sólo si la buscamos en el lugar correcto. Las secciones incluyen: La búsqueda contínua, Nuestro dilema, ¿Cómo es Dios?, ¿Qué hizo Jesús por nosotros?, Cómo encontrar el camino de vuelta, Cómo encontrar la paz, El cielo, nuestra esperanza, El secreto de la paz personal ofrece una mirada en cómo vivir la vida en la plenitud de Dios.','','libro30a.png','libro30b.png','producto-3',35000,'0','visited',2),
('Emprender tu propio negocio','Walter Grant','5','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','','libro40a.png','libro40b.png','producto-4',18000,'12','in-sale',2),
('Padre rico, padre pobre','Robert T. Kiyosaki','1','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','','libro50a.png','libro50b.png','producto-5',32000,'0','visited',2),
('Controlar la ansiedad','Ronna Browning','4','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','','libro60a.png','libro60a.png','producto-6',18000,'15','in-sale',2),
('El metodo rico','Richard Gracia - Diego Gracia','7','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','','libro70a.png','libro70a.png','producto-7',54000,'0','visited',2),
('Yo antes de ti','Jojo Moyes','1','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','','libro80a.png','libro80a.png','producto-8',32000,'8','visited',2),
('Mi viaje sin ti','Alejandro Sequeira','1','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','','libro90a.png','libro90a.png','producto-9',42000,'5','visited',2),
('El poder de creer en ti','Daniel J. Martin','5','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident debitis nihil incidunt quisquam ab reiciendis consequuntur iure.','','libro100a.png','libro100a.png','producto-10',25000,'0','in-sale',2),
('90 minutos en el cielo','Cecil Murphey','5','En los diez años transcurridos desde la publicación de 90 Minutos en el Cielo, millones de personas en todo el mundo han leído la increíble historia real de la experiencia de Don Piper con la muerte y la vida, y al leerla han descubierto que sus propias vidas han cambiado.','Después de que un camión chocara con el coche de Don Piper, éste fue declarado muerto en el lugar de los hechos. Durante los siguientes noventa minutos, experimentó las glorias del cielo. De vuelta a la tierra, un ministro que pasaba por allí se sintió impulsado a detenerse y rezar por la víctima del accidente, a pesar de que le habían dicho que Piper estaba muerto. Milagrosamente, Piper volvió a la vida, y el placer del cielo fue sustituido por una larga y dolorosa recuperación. Con una actualización personal de Don sobre el impacto que el libro ha tenido en él, en su familia y en los millones de personas que han escuchado su historia, incluso aquellos que han leído el libro original querrán formar parte de la historia continua de 90 minutos en el cielo con esta nueva edición.','','libro110a.png','libro110b.png','producto-110',25000,'15','in-sale',2),
('El fin de la Inflacion','Javier Milei','2','Dar la pelea contra la inflación y volver a ser un país en serio. Plantándole cara a la casta política, peleando contra un supuesto sentido común de época que está destruyendo la Argentina y retando a duelo de ideas a colegas economistas, el candidato a la presidencia de la Nación presenta aquí tres textos que conforman el núcleo de lo que podría ser leído como un programa de gobierno, y que en realidad es mucho más que eso: se trata de un ataque frontal a la inflación, ese mal que corroe día a día la vida de millones y millones de argentinos.','Dar la pelea contra la inflación y volver a ser un país en serio. Plantándole cara a la casta política, peleando contra un supuesto sentido común de época que está destruyendo la Argentina y retando a duelo de ideas a colegas economistas, el candidato a la presidencia de la Nación presenta aquí tres textos que conforman el núcleo de lo que podría ser leído como un programa de gobierno, y que en realidad es mucho más que eso: se trata de un ataque frontal a la inflación, ese mal que corroe día a día la vida de millones y millones de argentinos. No será una lucha fácil, advierte Javier Milei: demasiados intereses enquistados, privilegios que llevan décadas, miserias corporativas. Pero hay una buena noticia: dar la pelea contra la inflación, recuperar la libertad de elegir qué hacer con nuestro dinero y terminar con las mentiras de una eco-nomía intoxicada por la política colocarán los cimientos para volver a ser un gran país. “Cuando los salarios en dólares vuelen, habrá una fuerte caída de la pobreza y la indigencia y una ganancia en bienestar enorme, por el solo hecho de haber realizado un cambio monetario que termine con la estafa”.','','libro3.png','libro3.png','producto-3',6450,'0','in-sale',2),
('El Eternauta','Hector G. Oesterheld','5','REGRESA EL CLÁSICO ARGENTINO DE LA CIENCIA FICCIÓN.De vuelta en 1959, Juan Salvo, el eternauta, ha olvidado la nevada mortal que arrasará el futuro.','REGRESA EL CLÁSICO ARGENTINO DE LA CIENCIA FICCIÓN.De vuelta en 1959, Juan Salvo, el eternauta, ha olvidado la nevada mortal que arrasará el futuro. Sin embargo, Germán no puede dejar de pensar en todo lo que el viajero del tiempo le ha contado, e intenta por todos los medios hacerle recordar. Pero el destino les tiene preparado un nuevo viaje que los transportará al Buenos Aires de mucho después de la terrible nevada. En esta segunda parte del clásico argentino de la ciencia fi cción, El eternauta, H. G. Oesterheld y F. Solano López vuelven a sumergirnos en un ambiente postapocalíptico donde priman la lucha por la supervivencia y la dignidad.','','libro8.png','','producto-8',5400,'14','visited',2),
('Chainsaw Man 01','Tatsuki Fujimoto','5','Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man!','Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil Pochita. He’s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!','','libro9.png','','producto-9',2800,'15','visited',2),
('Messirve','Verónica de Andrés, Florencia Andrés','10','Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man!','Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil Pochita. He’s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!','','libro9a.png','','producto-9a',5950,'15','in-sale',2),
('Enferme para sanar','Marina Borensztein','9','El 29 de noviembre de 2011 comencé a escribir este diario que se convirtió en un exitoso libro. Pasaron casi exactamente ocho años desde aquel día en el que no imaginé el rumbo que tomaría mi vida. Jamás sospeché que sería el comienzo de un gran desarrollo personal y profesional. Jamás imaginé que ese diario cambiaría mi vida y la de tantas personas.','A los dos meses de casarse con el amor de su vida y a poco de cumplir cuarenta y seis años, Marina Borensztein recibió una noticia tan inesperada como dramática: tenía cáncer de mama. Luego de un momento inicial de desconcierto, Marina fue acusando el golpe. Mientras hacía lo que tenía que hacer para curar su cuerpo físico –cirugía, rayos, tratamiento hormonal–, empezó una intensa búsqueda espiritual. Con mayor o menor suerte, incursionó en disciplinas diversas que abarcaron desde el yoga y la meditación hasta el reiki, la acupuntura, la terapia con flores, la homeopatía, el psicoanálisis y la alimentación consciente.','','libro3a.png','libro3b1.png','producto-3a',5950,'15','in-sale',2),
('Nadie puede hacerte infeliz','Claudio Maria Dominguez','9','El 29 de noviembre de 2011 comencé a escribir este diario que se convirtió en un exitoso libro. Pasaron casi exactamente ocho años desde aquel día en el que no imaginé el rumbo que tomaría mi vida. Jamás sospeché que sería el comienzo de un gran desarrollo personal y profesional. Jamás imaginé que ese diario cambiaría mi vida y la de tantas personas.','A los dos meses de casarse con el amor de su vida y a poco de cumplir cuarenta y seis años, Marina Borensztein recibió una noticia tan inesperada como dramática: tenía cáncer de mama. Luego de un momento inicial de desconcierto, Marina fue acusando el golpe. Mientras hacía lo que tenía que hacer para curar su cuerpo físico –cirugía, rayos, tratamiento hormonal–, empezó una intensa búsqueda espiritual. Con mayor o menor suerte, incursionó en disciplinas diversas que abarcaron desde el yoga y la meditación hasta el reiki, la acupuntura, la terapia con flores, la homeopatía, el psicoanálisis y la alimentación consciente.','','libro4.png','','producto-4',2555,'15','visited',2),
('El Poder del metabolismo','Frank Suarez','9','En un mundo de controversias en el tema de la obesidad, El Poder del Metabolismo registra las tecnicas y factores que ayudan a recuperar el metabolismo, basadas en EXPERIENCIA Y OBSERVACIONES de lo que ha funcionado en mas de 25,000 personas.','Las tecnicas para bajar de peso de forma natural vienen descritas en este Best-Seller de Puerto Rico. Los temas incluyen una dieta con la que se puede vivir, por que las grasas no son las culpables de la obesidad, la diferencia entre bajar de peso y adelgazar, los alimentos que son fuentes de energia para el metabolismo, el hongo candida albicans, entre otros. El libro define las causas y soluciones al problema del metabolismo lento que tiene algunos haciendo dieta de por vida mientras otros son flacos coman lo que coman. Por lo tanto se concluye que bajar de peso no tiene que ver solo con lo que usted come. El autor, un especialista en obesidad y metabolismo, ha incluido recomendaciones especiales para personas con diabetes o hipotiroidismo.','','libro6.png','libro6b.png','producto-6',2050,'15','visited',2),
('Titulo de prueba','yo','2','descripcion de prueba','descripcion detallada del libro de prueba descripcion detallada del libro de prueba descripcion detallada del libro de prueba descripcion detallada del libro de prueba','','1704474224885-nosoyviejo.jpg','1704474224889-lorvale.jpg','','35500','5','',2);
INSERT INTO users(fullName,email,password,category_id,avatar) VALUES 
('Fin Bulward','fbulward0@pagesperso-orange.fr','$2a$10$/PcwNFkUFIf5O/nPJ.jFh.ie2qJvCjN1HphXFDuwjRbB1AgyXzbku','2','michael.jpg'),
('Kelby Pancoast','kpancoast1@techcrunch.com','$2a$10$/PcwNFkUFIf5O/nPJ.jFh.ie2qJvCjN1HphXFDuwjRbB1AgyXzbku',2,'jake.jpg'),
('Barbabra Cardenosa','bcardenosa2@java.com','$2a$10$/PcwNFkUFIf5O/nPJ.jFh.ie2qJvCjN1HphXFDuwjRbB1AgyXzbku','2','kipa.jpg'),
('Yoda','cliente@gmail.com','$2a$10$/PcwNFkUFIf5O/nPJ.jFh.ie2qJvCjN1HphXFDuwjRbB1AgyXzbku','2','cliente.jpg'),
('Miguel Alejandro Nieva','admin@gmail.com','$2a$10$/PcwNFkUFIf5O/nPJ.jFh.ie2qJvCjN1HphXFDuwjRbB1AgyXzbku','1','admin.jpg');
insert into payments (id, name) values (1, 'Efectivo');
insert into payments (id, name) values (2, 'Tarjeta de Debito');
insert into payments (id, name) values (3, 'Tarjeta de Credito');

