-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 19:53:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DigitalBooks_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DigitalBooks_db` ;

-- -----------------------------------------------------
-- Schema DigitalHouse_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DigitalBooks_db` DEFAULT CHARACTER SET utf8 ;
USE `DigitalBooks_db` ;

-- -----------------------------------------------------
-- Table `cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cart` ;

CREATE TABLE IF NOT EXISTS `cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `detailCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detailCart` ;

CREATE TABLE IF NOT EXISTS `detailCart` (
  `cart_item_id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`cart_item_id`));


-- -----------------------------------------------------
-- Table `detailOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detailOrder` ;

CREATE TABLE IF NOT EXISTS `detailOrder` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  `priceBuy` DECIMAL(8,2) NULL,
  PRIMARY KEY (`order_item_id`));


-- -----------------------------------------------------
-- Table `genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genres` ;

CREATE TABLE IF NOT EXISTS `genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `shippinAddress` NVARCHAR(350) NULL,
  `status` VARCHAR(10) NULL,
  `dateOrder` DATE NULL,
  `amountTotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payments` ;

CREATE TABLE IF NOT EXISTS `payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `genre_id` INT NOT NULL,
  `description` TEXT NULL,
  `descriptionD` TEXT NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `imgTop` VARCHAR(45) NULL,
  `imgBack` VARCHAR(45) NULL,
  `alt` VARCHAR(20) NULL,
  `price` DOUBLE NOT NULL,
  `discount` DOUBLE NULL,
  `category` VARCHAR(40) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `category_id` INT NOT NULL,
  `avatar` VARCHAR(65) NULL,
  PRIMARY KEY (`id`));

--
-- Estructura de tabla para la tabla `sequelizemeta`
--

CREATE TABLE `sequelizemeta` (
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Volcado de datos para la tabla `sequelizemeta`
--

INSERT INTO `sequelizemeta` (`name`) VALUES
('01_categorias.js'),
('02_productos.js'),
('03_usuarios.js'),
('04_generos.js'),
('05_carrocompras.js'),
('06_pedidos.js'),
('07_carrodetalle.js'),
('08_pedidodetalle.js');

-- --------------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
