module.exports = {
    up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert("detailCart", [
        { cart_id: 1, product_id: 16, cantidad: 2 },
        { cart_id: 2, product_id: 18, cantidad: 2 },
        { cart_id: 3, product_id: 7, cantidad: 3 },
        { cart_id: 4, product_id: 13, cantidad: 3 },
        { cart_id: 5, product_id: 12, cantidad: 2 },
        { cart_id: 1, product_id: 1, cantidad: 2 },
        { cart_id: 2, product_id: 14, cantidad: 3 },
        { cart_id: 3, product_id: 15, cantidad: 4 },
        { cart_id: 4, product_id: 18, cantidad: 4 },
        { cart_id: 5, product_id: 8, cantidad: 2 },
        { cart_id: 6, product_id: 3, cantidad: 2 },
        { cart_id: 7, product_id: 17, cantidad: 2 },
        { cart_id: 8, product_id: 12, cantidad: 3 },
        { cart_id: 9, product_id: 13, cantidad: 3 },
        { cart_id: 10, product_id: 15, cantidad: 4 },
        { cart_id: 6, product_id: 14, cantidad: 4 },
        { cart_id: 7, product_id: 3, cantidad: 2 },
        { cart_id: 8, product_id: 13, cantidad: 3 },
        { cart_id: 9, product_id: 13, cantidad: 3 },
        { cart_id: 10, product_id: 7, cantidad: 3 },
        { cart_id: 11, product_id: 6, cantidad: 2 },
        { cart_id: 12, product_id: 2, cantidad: 3 },
        { cart_id: 13, product_id: 18, cantidad: 4 },
        { cart_id: 14, product_id: 14, cantidad: 4 },
        { cart_id: 15, product_id: 4, cantidad: 2 },
        { cart_id: 16, product_id: 2, cantidad: 2 },
        { cart_id: 17, product_id: 8, cantidad: 2 },
        { cart_id: 18, product_id: 17, cantidad: 3 },
        { cart_id: 19, product_id: 18, cantidad: 3 },
        { cart_id: 20, product_id: 10, cantidad: 4 },
        { cart_id: 11, product_id: 4, cantidad: 2 },
        { cart_id: 12, product_id: 17, cantidad: 3 },
        { cart_id: 13, product_id: 10, cantidad: 4 },
        { cart_id: 14, product_id: 16, cantidad: 4 },
        { cart_id: 15, product_id: 2, cantidad: 2 },
        { cart_id: 16, product_id: 18, cantidad: 2 },
        { cart_id: 17, product_id: 2, cantidad: 2 },
        { cart_id: 18, product_id: 14, cantidad: 3 },
        { cart_id: 19, product_id: 12, cantidad: 3 },
        { cart_id: 20, product_id: 5, cantidad: 4 },
      ]);
    },
    down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete("detailCart", null, {});
    },
  };
